name: build_project
on:
  pull_request:
    types: closed
    branches:
      - main

  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: multiple command
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd Elettrotecnica-UNISA
            git checkout main
            git fetch --prune
            git pull
            docker compose up -d --build